### ISSUE TITLE
Site https://donate.adadevelopersacademy.org/ is down

### ISSUE THREAD

**Issue by joelibaceta** [Ada-Developers-Academy/ada-donate#25]
<img width="733" alt="captura de pantalla 2018-11-26 a la s 22 26 09" src="https://user-images.githubusercontent.com/864790/49052361-477f1a00-f1ca-11e8-9fde-5782e2e1a5cf.png">

**Comment by Hamled** [comment]
Thank you for the issue. The website is actually at https://adaloanfund.org/ (I have updated the project homepage to reflect this).
